#!/bin/bash

sum=0
TMP1=./tempfile #creates variable
echo -e "8\n7\n6\n100" > $TMP1     #things are echoed into variable temp1

while read num
do
    echo "In Loop"
    echo "num: $num"
    sum='expr $sum + $num'
    echo "sum: $sum:"
    echo -e "End of Loop\n"
done < $TMP1   #take temp1 as argument 
