#!/bin/bash

#converts a row file into a column file ./tempinputfile to ./tempcolfile
#then back into a row file ./temprowfile<PID>
inputFile="tempinputfile"
tempCol="tempcolfile"
tempRow="temprowfile"

#make the input row file
echo -e "1\t2\t3\t4\t5" > $inputFile

#append each nuber onto the end of a temporary column file but "cut" specific columns
cut -c 1 $inputFile > $tempCol  # -c looks for characters, -f looks for fields
cut -c 3 $inputFile >> $tempCol # -f should be used for assignment
cut -c 7 $inputFile >> $tempCol
cut -c 9 $inputFile >> $tempCol

#convert col file back into row file
cat $tempCol | tr '\n' '\t' > "$tempRow$$" #tr transforms \n with \t #"*$$" gives unique suffix to tempRow file

#add a newline char to end of row file for easy printing
echo >> "$tempRow$$"

